# Generated by Django 5.0.6 on 2024-06-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="interaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-created_at"]},
        ),
    ]
